### ISSUE TITLE
Parse Markdown on item description

### ISSUE THREAD

**Issue by roiLeo** [kodadot/fandom#25]
![Screenshot 2023-06-29 at 15 54 11](https://github.com/kodadot/fandom/assets/22471030/f3615d31-bb8a-4db5-8193-eba6d61988ec)

**Comment by vikiival** [comment]
![Screenshot 2023-06-29 at 15 52 48](https://github.com/kodadot/fandom/assets/22471030/aa33f3ea-ba9f-4284-ba10-6b94f5c193a2)

<img width="1072" alt="Screenshot 2023-06-29 at 15 53 54" src="https://github.com/kodadot/fandom/assets/22471030/bd671bd7-127e-470b-a318-8fce9e5b212d">
